export const ADD_SCHOOL = 'SCHOOL::ADD_SCHOOL';
export const LOADING_SCHOOL = 'SCHOOL::LOADING_SCHOOL';
export const GOT_SCHOOLS_TOTAL = 'SCHOOL::GOT_SCHOOLS_TOTAL';

export const ADD_LANGUAGES = 'LANGUAGE::ADD_LANGUAGES';
export const LOADING_LANGUAGE = 'LANGUAGE::LOADING_LANGUAGE';
export const GOT_LANGUAGES_TOTAL = 'LANGUAGE::GOT_LANGUAGES_TOTAL';

export const ADD_SKILLS = 'SKILL::ADD_SKILLS';
export const LOADING_SKILL = 'SKILL::LOADING_SKILL';
export const GOT_SKILLS_TOTAL = 'SKILL::GOT_SKILLS_TOTAL';

export const ADD_CERTIFICATIONS = 'CERTIFICATION::ADD_CERTIFICATIONS';
export const LOADING_CERTIFICATION = 'CERTIFICATION::LOADING_CERTIFICATION';
export const GOT_CERTIFICATIONS_TOTAL = 'CERTIFICATION::GOT_CERTIFICATIONS_TOTAL';
