export const ADD_SCHOOL = 'SCHOOL::ADD_SCHOOL';
export const LOADING_SCHOOL = 'SCHOOL::LOADING_SCHOOL';
export const GOT_SCHOOLS_TOTAL = 'SCHOOL::GOT_SCHOOLS_TOTAL';

export const ADD_LANGUAGES = 'LANGUAGE::ADD_LANGUAGES';
export const LOADING_LANGUAGE = 'LANGUAGE::LOADING_LANGUAGE';
export const GOT_LANGUAGE_TOTAL = 'LANGUAGE::GOT_LANGUAGE_TOTAL';
